---
title: "Final Project"
author: "Entong Li, Jingyu Xie, Xindi Lu, Zijia Cao"
date: "12/1/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, autodep = TRUE)
library(tidyverse)
library(MASS)
library(broom)
library(scales)
library(GGally)
library(gridExtra)
google <- read.csv("data/googleplaystore.csv", header = TRUE)
google <- na.omit(google)
google <- google[-c(11,12,13)] %>% filter(0<= Rating, 5>= Rating)
cb_palette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbp <- function(x) scale_fill_manual(values = cb_palette)
```


```{r}
#Make Price as numeric variable:
google$Price <- recode_factor(google$Price, `0` = "$0", `Everyone` = "$0")
Price2 <- as.numeric(gsub("\\$","",google$Price))
google$Price <- Price2
google$ForP <- ifelse(google$Price == 0, "Free","Paid")
```

```{r}
#recode the levels of Installs:
google$Installs <- factor(google$Installs, levels = c("1+","5+","10+", "50+", "100+", "500+", "1,000+", "5,000+", "10,000+", "50,000+", "100,000+", "500,000+", "1,000,000+", "5,000,000+", "10,000,000+", "50,000,000+", "100,000,000+", "500,000,000+", "1,000,000,000+" ))
```

```{r}
#Make Reviews as numeric variables:
Reviews2 <- as.numeric(as.character(google$Reviews))
google$Reviews <- Reviews2
```

```{r}
#Divede Size into two groups: Mbs and kbs, and make the Size become a numeric variable:
google <- google %>% filter(Size != "Varies with device", Size != "1,000+")
google$Size <- as.character(google$Size)
google$Size.M <- ifelse(grepl("M", google$Size), "M","k")
Size1 <- as.numeric(gsub("[k|M]","",google$Size))
google$Size <- Size1
```

```{r}
google$Category <- as.character(google$Category)
google.part <- google %>% filter(google$Category %in% c("FAMILY","GAME","TOOLS","HEALTH_AND_FITNESS","SPORTS","SOCIAL", "COMMUNICATION","DATING"), Price <= 10)
google.part$Category <- as.factor(recode(google.part$Category, "HEALTH_AND_FITNESS" = "FITNESS","SPORTS" = "FITNESS","SOCIAL" = "MEDIA", "COMMUNICATION" = "MEDIA","DATING" = "MEDIA"))
```


```{r}
google.part$Rating.range <- cut_interval(google.part$Rating, length = 1.0)
```

## Free vs Paid:

```{r}
ggplot(google.part, aes(x = ForP, group = Category, color = Category,fill = Category)) + geom_bar()
```

## Size: Mbs vs. Kbs:

```{r}
ggplot(data = google.part, aes(x = Size.M, group = Category, color = Category, fill = Category)) + geom_bar()
google.part <- google.part %>% filter(google.part$Size.M == "M")
```

As the number of apps that size are counted by kbs is pretty small, we will include the apps that size are counted by Mbs. 

## Rating explanatory:

```{r}
ggpairs(google.part[c(2,3,5,8)])
```

### Rating and Free or Paid:

```{r}
ggplot(data = google.part, aes(x = Rating,..count.., fill = Type )) + geom_density(position = "fill") + labs(title = "Density of rating based on type")
ggplot(data = google.part, aes(x = Rating,..count.., fill = Category )) + geom_density(position = "fill") + labs(fill = "Category") + labs(title = "Density of rating based on category")
ggplot(data = google.part, aes(x = Rating, color = Category,fill = Category))+ geom_bar()
```

```{r}
google.part <- google.part%>%filter(Size <= 100)
ggplot(data = google.part, aes(x = Size, y = Rating, color = Category)) + geom_point() + geom_smooth(method = 'lm',se = FALSE,color = "black") + facet_wrap(~Category) + xlab("Size(MB)")
```

```{r}
google.part$indicator <- ifelse(google.part$Type == "Free", 0 , 1)
glm(weights = Reviews, Rating ~ indicator + Price + Size + Category, data = google.part)
glm(weights = Reviews, Rating ~ Price + Size + Category, data = google.part)
```

```{r}
rlm(Rating~Price + Size + Category, weights = Reviews, data = google.part, psi = psi.bisquare)
```


```{r}
# Content Rating and Rating
ggplot(google.part, aes(Rating, fill = Content.Rating)) + geom_density() + facet_grid(Content.Rating ~ .) + scale_fill_manual(values = cb_palette)

# category and rating
#ggplot(google.part, aes(Rating, fill = Category)) + geom_density() + facet_grid(Category ~ .) + scale_fill_manual(values = cb_palette)
ggplot(google.part, aes(Rating, ..count.., fill = Category)) + geom_density(position = "stack") + scale_fill_manual(values = cb_palette)

# relationship between price and rating (Paid App)
Paid <- google.part %>%
  filter(Type == "Paid")
ggplot(Paid, aes(Price, Rating, color = Category)) + geom_point() + geom_smooth() + scale_color_manual(values = cb_palette)
```


```{r}
ggplot(data = google.part%>%filter(Type == "Free"), aes(x = Rating, group = Category, color = Category, fill = Category)) + geom_density(position = "fill")
ggplot(data = google.part%>%filter(Type == "Paid"), aes(x = Rating, group = Category, color = Category, fill = Category)) + geom_density(position = "fill")
```

```{r}
ggplot(data = google.part, aes( x = Rating.range, group = Type, color = Type)) + geom_line(show.legend = FALSE,aes(y = ..prop..), stat = "count") + geom_text(aes(label = scales::percent(..prop..), y = ..prop..), stat = "count") + labs(fill = "Rating range", title = "Percentage of different rating range") + cbp()+ ylab("Percentage")+scale_y_continuous(labels=scales::percent)

ggplot(data = google.part%>%filter(Type == "Free"), aes( x = Rating.range, group = Category)) + geom_bar(show.legend = FALSE,aes(y = ..prop.., fill = factor(..x..)), stat = "count") + geom_text(aes(label = scales::percent(..prop..), y = ..prop..), stat = "count") + facet_wrap(~Category) + labs(fill = "Rating range", title = "Percentage of different rating range within Category\n(For Free Apps)") + ylab("Percentage")+scale_y_continuous(labels=scales::percent) +cbp()

ggplot(data = google.part%>%filter(Type == "Paid"), aes( x = Rating.range, group = Category)) + geom_bar(show.legend = FALSE,aes(y = ..prop.., fill = factor(..x..)), stat = "count") + geom_text(aes(label = scales::percent(..prop..), y = ..prop..), stat = "count") + facet_wrap(~Category) + labs(fill = "Rating range", title = "Percentage of different rating range within Category\n(For Paid Apps)") + ylab("Percentage")+scale_y_continuous(labels=scales::percent) +cbp()

ggplot(data = google.part, aes( x = Rating.range, group = Category)) + geom_line(show.legend = FALSE,aes(y = ..prop.., fill = factor(..x..)), stat = "count") + geom_text(aes(label = scales::percent(..prop..), y = ..prop..), stat = "count") + facet_wrap(~Category) + labs(fill = "Rating range", title = "Percentage of different rating range within Category\n(For Paid Apps)") + ylab("Percentage")+scale_y_continuous(labels=scales::percent) +cbp()
```

```{r}
prop.of.free <- as.data.frame(matrix(c("FAMILY",0.6,2.8,27.4,69.2,"FITNESS",0.7,5.5,20.5,73.3,"GAME",0.2,0.8,19.3,79.7,"MEDIA",1.2,4.2,26.3,68.3, "TOOLS",1.9,6.3,32.3,59.5),dimnames = list(c(),c("Category","[1,2]","(2,3]","(3,4]","(4,5]")), ncol = 5, byrow = TRUE))

prop.of.paid <- as.data.frame(matrix(c("FAMILY",1.5,3.8,11.4,83.3,"FITNESS",0,0,25.9,74.1,"GAME",0,0,18.1,81.9,"MEDIA",0,18.8,31.2,50.0,"TOOLS", 2.5,2.5,20.0,75.0),dimnames = list(c(),c("Category","[1,2]","(2,3]","(3,4]","(4,5]")), ncol = 5, byrow = TRUE))

G1 <- gather(prop.of.free[c(2:5)], key = "range",value = "prop")
g.cate <- rep(c("FAMILY","FITNESS","GAME","MEDIA","TOOLS"), 4)
G1$category <- g.cate
G1$type <- "Free"
G2 <- gather(prop.of.paid[c(2:5)], key = "range",value = "prop")
G2$type <- "Paid"
G2$category <- g.cate
G <- rbind(G1,G2)
G$prop <- as.numeric(G$prop)
G$range <- factor(G$range, levels = c("[1,2]","(2,3]", "(3,4]", "(4,5]"))
ggplot(data = G, aes(x = range, y = prop, group = type, color = type)) + geom_line() + facet_wrap(~category) + ylab("Percentage (%)") + xlab("Rating Range") + labs(title = "Porportion of rating range")
```



```{r, fig.width=8, fig.height=5}
type <- ggplot(google.part, aes(Type, fill = Type)) + theme(axis.text.x = element_blank()) + 
          geom_bar(aes(y = (..count..)/sum(..count..)))  + ylab("Percentage") +
          scale_y_continuous(labels=scales::percent) + geom_text(aes(label = percent((..count..)/sum(..count..)), y = (..count..)/sum(..count..)), stat = "count") + labs(title = "Percentage of Free/Paid Apps")

category <- ggplot(google.part, aes(Category, fill = Category)) + theme(axis.text.x = element_blank()) +
          geom_bar(aes(y = (..count..)/sum(..count..)))  + ylab("Percentage") +
          scale_y_continuous(labels=scales::percent) #+geom_text(aes(label = percent((..count..)/sum(..count..)), y = (..count..)/sum(..count..)), stat = "count") + labs(title = "Percentage of Category")

ratingR <- ggplot(google.part, aes(Rating.range, fill = Rating.range)) + theme(axis.text.x = element_blank()) +geom_bar(aes(y = (..count..)/sum(..count..))) + ylab("Percentage") + scale_y_continuous(labels=scales::percent) +geom_text(aes(label = percent((..count..)/sum(..count..)), y = (..count..)/sum(..count..)), stat = "count") + labs(title = "Percentage of Rating range") 
grid.arrange(type, ratingR, ncol = 2)
```

```{r}
ggplot(data = google.part%>%filter(Type == "Paid"), aes( x = Price, y = Rating, color = Category, group = Category)) + geom_point() + geom_smooth(se = FALSE, method = "lm", color = "black") + facet_wrap(~Category) + xlab("Price ($)")
ggplot(data = google.part%>%filter(Type == "Paid"), aes( x = Price, y = Rating)) + geom_point() + geom_smooth(method = "loess", se = FALSE)+ xlab("Price ($)")
```


